name = "blog-ikber"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

services = [
  { binding = "WORKER_SELF_REFERENCE", service = "blog-ikber" },
]

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "0b92cec8-41fe-4354-b844-fea2e4c7024e"
migrations_dir = "./migrations"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "blog-images"

[observability]
enabled = false

[vars]
NEXT_PUBLIC_GISCUS_REPO = "WeitaoYan/blog-ikber"
NEXT_PUBLIC_GISCUS_REPO_ID = "R_kgDOSOAx0w"
NEXT_PUBLIC_GISCUS_CATEGORY = "Announcements"
NEXT_PUBLIC_GISCUS_CATEGORY_ID = "DIC_kwDOSOAx084C7zii"
R2_PUBLIC_URL = "https://static.ikber.cc"