name = "blog-ikber"
compatibility_date = "2026-04-28"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

services = [
  { binding = "WORKER_SELF_REFERENCE", service = "blog-ikber" },
]

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "0b92cec8-41fe-4354-b844-fea2e4c7024e"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "blog-images"
