name = "blog-ikber"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"
assets = { directory = ".open-next/assets", binding = "ASSETS" }

services = [
  { binding = "WORKER_SELF_REFERENCE", service = "blog-ikber" },
]

[[d1_databases]]
binding = "DB"
database_name = "blog-db"
database_id = "your-database-id"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "blog-images"
